server:
  port: ${PORT}
  ssl:
    enabled: true
    key-store-type: JKS
    key-store: ${SSL_KEY_PATH}
    key-store-password: ${SSL_KEY_PASSWORD}

spring:
  datasource:
    url: ${DB_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
